### ISSUE TITLE
그림이 하나도 안보임.

### ISSUE THREAD

**Issue by bemoregt** [superdev-zz/computer-vision#1]
Hi, @superdev-zz 

그림이 하나도 안보임.

결과 이미지 하나 올려주길..

설현도 좋구~

Best,
@bemoregt.

**Comment by superdev-zz** [comment]
> Hi, @superdev-zz
> 
> 그림이 하나도 안보임.
> 
> 결과 이미지 하나 올려주길..
> 
> 설현도 좋구~
> 
> Best,
> @bemoregt.
